### ISSUE TITLE
Enforce stronger password

### ISSUE THREAD

**Issue by HR** [HR/Crypter#29]
Ensure that there is at least one capital letter used in password.

**Comment by HR** [comment]
Fixed by https://github.com/HR/Crypter/commit/abc22f4d944dfffee8cb1dbea17e5220f845d8f6

**Comment by EdOverflow** [comment]
I do not agree with the current password guidelines.

In case you missed it, NIST updated their password guidelines here: https://pages.nist.gov/800-63-3/sp800-63b.html#memorized-secret-verifiers

> Verifiers SHOULD NOT impose other composition rules (mixtures of different character types, for example) on memorized secrets.

**Comment by HR** [comment]
@EdOverflow please open a new issue for discussing this (different matter).

**Comment by HR** [comment]
@EdOverflow would also appreciate your input on https://github.com/HR/Crypter/issues/26
